name: samgeo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - rasterio
  - geopandas
  - matplotlib
  - scikit-image
  - scikit-learn
  - scipy
  - psutil
  - pyproj
  - pip
  - pip:
      - segment-geospatial[samgeo2]
